#!/usr/bin/env bash

declare -a VERSIONS=(
    "1.2.1"
    "1.2.2"
    "1.2.3"
    "1.2.4"
    "1.2.5"
)

VERSION="1.2.3"
VERSION_PARTS=( ${VERSION//./ } )

printf "%s\n" "${VERSIONS[@]}" \
    | awk -F"." \
        -v major="${VERSION_PARTS[0]}" \
        -v minor="${VERSION_PARTS[1]}" \
        -v patch="${VERSION_PARTS[2]}" \
        '$1 >= major && $2 >= minor && $3 >= patch {print $1,$2,$3}'