#!/usr/bin/env bash

# Not in interactive shell so need to boostrap rbenv
# ( see shell dotfiles )
source "$DOTFILES_CONFIG_HOME/bash_rbenv.sh"

# Absolute bare minimum gem packages to support global environment
# NOTE: Ensure installed with --user
# NOTE: Relies on PATH being set correctly
echo "Installing system ruby packages" >&2
gem install --user tmuxinator
