#!/usr/bin/env bash

# RBENV installer

set -eou pipefail

echo "Installing rbenv" >&2

[ ! -d "$RBENV_ROOT" ] && mkdir -p "$RBENV_ROOT" >/dev/null

# Install rbenv
git clone https://github.com/rbenv/rbenv.git "$RBENV_ROOT"

# Compile dynamic bash rbenv extension
cd "$RBENV_ROOT" && src/configure && make -C src

# Install ruby-build to get the `rbenv install` command
[ ! -d "$RBENV_ROOT/plugins" ] && mkdir -p "$RBENV_ROOT/plugins" >/dev/null
git clone https://github.com/rbenv/ruby-build.git \
    "$RBENV_ROOT/plugins/ruby-build"
