#!/usr/bin/env bash

# Not in interactive shell so need to boostrap RVM
# ( see shell dotfiles )
source "$DOTFILES_CONFIG_HOME/bash_rvm.sh"

echo "Provisioning rvm environment" >&2

# Configure RVM to automatically install dependent packages
# ( e.g. openssl to support download verification )
echo "Configuring RVM" >&2
rvm autolibs packages

# Update RVM to latest stable build
# Configure the installer to not setup rvm in the dotfiles
# ( would otherwise write to ~/.profile )
export rvm_ignore_dotfiles=yes
echo "Patching RVM to latest version" >&2
rvm get stable

# Setup default gems that will be installed with each new Ruby version
# Note that this file might get overwritten with subsequent updates of RVM
# ( e.g. via rvm get stable )
cat << EOF >> ~/.rvm/gemsets/default.gems
bundler
tmuxinator
EOF

# Get the latest stable ruby version
echo "Installing latest stable ruby version" >&2
# 0: only verified
# 1: allow missing checksums
# 2: allow failed checksums
rvm install --latest --verify-downloads 1 ruby

# Set default ruby version
# Switch back using:
# rvm use system
rvm use --default ruby

# Generate ri docs
echo "Generating ri docs" >&2
gem rdoc --all --ri --no-rdoc
