#!/usr/bin/env bash

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_PATH" || exit 1

if (( $(id -u) != 0 )); then
  echo "This script must be run as root"
  echo "Please use sudo or su"
  exit 1
fi

function strip_whitespace()
{
  echo "${1// }"
}

function user_pause()
{
  read -r -p "Hit enter to continue "
}

function user_prompt()
{
  echo
  while [ -z "$(strip_whitespace $REPLY)" ]; do
    read -r -p "$1: "
  done
  echo "$answer"
}

function user_confirm()
{
  echo
  while [[ ! $REPLY =~ ^[YyNn]$ ]]; do
    read -r -p "$1 (y/n) "
  done
  [[ $REPLY =~ ^[Yy$ ]]
}

function ui()
{
  if [[ -z "$(git config user.name)" || \
    -z "$(git config user.email)" ]]; then
    git config --global user.name "$(user_prompt "Enter git user name")"
    git config --global user.email "$(user_prompt "Enter git email")"
  fi
}

function create_dotfiles_group()
{
  grep -q -F dotfiles /etc/group \
    || sudo groupadd dotfiles \
    || return

  sudo usermod -a -G dotfiles "${SUDO_USER:-$USER}"
}

function main()
{
  echo "INFO: Initializing all submodules..." >&2
  git submodule update --init --recursive || return

  ui || return

  create_dotfiles_group || return

  #echo "INFO: Setting up default ssh keypair" >&2
  #./scripts/setup-ssh-default-keypair "$GIT_EMAIL" || return

  echo "INFO: Setting up dotfiles" >&2
  ./scripts/setup-dotfiles dotfiles || return

  echo "INFO: Running all installers" >&2
  ./scripts/setup-installers || return
}

main "$@"
exit $?

