#!/usr/bin/env bash

# GitHub api rate check:
# curl https://api.github.com/rate_limit

set -eou pipefail

echo "Installing Docker" >&2

VERSION=
TAG=
GITHUB_META_URL="https://api.github.com/repos/docker/docker-ce/releases/latest"
REPOS_URL_TMPL='https://raw.githubusercontent.com/docker/docker-ce/$TAG'

# Get github meta into array as follows:
# 0: version
# 1: tag
# Curl returns: {
#   name: <version>,
#   tag_name: <tag_name> }
GITHUB_META=(` \
    curl -s "$GITHUB_META_URL" \
    | jq -r '.name, .tag_name'`)
VERSION="${GITHUB_META[0]}"
TAG="${GITHUB_META[1]}"
echo "Installing Docker version: $VERSION" >&2

# Remove older version of docker that might have
# come bundled with the OS
sudo apt-get remove -y \
    docker \
    docker-engine \
    docker.io

# Install Dockers GPG key
# Note APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE prevents apt-key warning when used
# non-interactively
sudo apt-key adv --fetch-keys https://download.docker.com/linux/ubuntu/gpg
if \
    ! APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=True \
        apt-key fingerprint "0EBFCD88" \
        | grep -q "9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88" ; then
    echo "Error importing docker gpg key" >&2
    false; exit
fi

# Add Docker repository
sudo add-apt-repository -y \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update -y

# Install Docker CE
# This will create the docker group
# and setup the docker service to autostart
sudo apt-get install -y docker-ce

# Add current user to docker group
# Note this wont take affect until subsequent login
sudo usermod -aG docker "$USER"

# Install Docker Bash completions
# Example
for file in docker ; do
    # -P: Prefix directory
    sudo wget "`eval echo $REPOS_URL_TMPL/components/cli/contrib/completion/bash/$file`" \
        -P /etc/bash_completion.d
done
