#!/usr/bin/env bash

# GitHub api rate check:
# curl https://api.github.com/rate_limit

set -eou pipefail

echo "Installing Docker Machine" >&2

PLATFORM="`uname -s`-`uname -m`"    # e.g. Linux-x86_64
VERSION=
TAG=
GITHUB_META_URL="https://api.github.com/repos/docker/machine/releases/latest"
GITHUB_META=
DOWNLOAD_URL=
REPOS_URL_TMPL='https://raw.githubusercontent.com/docker/machine/$TAG'

# Create temporary working directory
# Delete it on exit
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# Get github meta into array as follows:
# 0: version
# 1: tag_name
# 2: download url
# Curl returns: {
#   name: <version>,
#   tag_name: <tag_name>,
#   assets: [ { name: docker-machine-<platform>, browser_download_url: <url> } ] }
GITHUB_META=(` \
    curl -s "$GITHUB_META_URL" \
    | jq -r --arg NAME "docker-machine-$PLATFORM" \
        '.name, .tag_name, (.assets[] | select (.name==$NAME) | .browser_download_url)'`)

# Download Docker Machine
# Example:
# https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-Linux-x86_64
VERSION="${GITHUB_META[0]}"
TAG="${GITHUB_META[1]}"
DOWNLOAD_URL="${GITHUB_META[2]}"
echo "Installing Docker Machine version: $VERSION" >&2
echo "Using download url: $DOWNLOAD_URL" >&2
# -O: Output file
wget -O "$TMPDIR/docker-machine-$PLATFORM" "$DOWNLOAD_URL"

# Install Docker Machine
sudo install "$TMPDIR/docker-machine-$PLATFORM" /usr/local/bin/docker-machine

# Install Docker Machine completions and wrapper scripts
# Example:
# https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash
for file in docker-machine-wrapper.bash docker-machine.bash ; do
    # -P: Prefix directory
    sudo wget "`eval echo $REPOS_URL_TMPL/contrib/completion/bash/$file`" \
        -P /etc/bash_completion.d
done
