#!/usr/bin/env bash

# GitHub api rate check:
# curl https://api.github.com/rate_limit

set -eou pipefail

echo "Installing Docker Machine" >&2

PLATFORM="`uname -s`-`uname -m`"    # e.g. Linux-x86_64

DOCKER_MACHINE_VERSION=             # in format "MAJOR.MINOR.PATCH"
DOCKER_MACHINE_META_URL="https://api.github.com/repos/docker/machine/releases/latest"
DOCKER_MACHINE_META=
DOCKER_MACHINE_DOWNLOAD_URL=
DOCKER_MACHINE_URL_TMPL='https://raw.githubusercontent.com/docker/machine/v$DOCKER_MACHINE_VERSION'

# Create temporary working directory
# Delete it on exit
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# Get docker machine meta into array as follows:
# 0: version
# 1: download url
# Curl returns: {
#   name: v<version>,
#   assets: [ { name: docker-machine-<platform>, browser_download_url: <url> } ] }
DOCKER_MACHINE_META=(`curl -s "$DOCKER_MACHINE_META_URL" \
    | jq -r --arg NAME "docker-machine-$PLATFORM" '.name, (.assets[] | select (.name==$NAME) | .browser_download_url)'`)

# Download Docker Machine
# Example:
# https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-Linux-x86_64
DOCKER_MACHINE_VERSION="$(sed -nr "s/^v(.*)$/\1/p" <<<${DOCKER_MACHINE_META[0]})"
DOCKER_MACHINE_DOWNLOAD_URL="${DOCKER_MACHINE_META[1]}"
echo "Installing Docker Machine version $DOCKER_MACHINE_VERSION" >&2
echo "Using download url: $DOCKER_MACHINE_DOWNLOAD_URL" >&2
# -O: Output file
wget -O "$TMPDIR/docker-machine-$PLATFORM" "$DOCKER_MACHINE_DOWNLOAD_URL"

# Install Docker Machine
sudo install "$TMPDIR/docker-machine-$PLATFORM" /usr/local/bin/docker-machine

# Install Docker Machine completions and wrapper scripts
# Example:
# https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash
for file in docker-machine-wrapper.bash docker-machine.bash
do
    # -P: Prefix directory
    sudo wget "`eval echo $DOCKER_MACHINE_URL_TMPL/contrib/completion/bash/$file`" \
        -P /etc/bash_completion.d
done
