#!/usr/bin/env bash

# GitHub api rate check:
# curl https://api.github.com/rate_limit

set -eou pipefail

echo "Installing Docker Compose" >&2

PLATFORM="`uname -s`-`uname -m`"    # e.g. Linux-x86_64

VERSION=
TAG=
GITHUB_META_URL="https://api.github.com/repos/docker/compose/releases/latest"
GITHUB_META=
DOWNLOAD_URL=
REPOS_URL_TMPL='https://raw.githubusercontent.com/docker/compose/$TAG'

# Create temporary working directory
# Delete it on exit
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# Get github meta into array as follows:
# 0: version
# 1: tag_name
# 2: download url
# Curl returns: {
#   name: <version>,
#   tag_name: <tag_name>,
#   assets: [ { name: docker-compose-<platform>, browser_download_url: <url> } ] }
GITHUB_META=(` \
    curl -s "$GITHUB_META_URL" \
    | jq -r --arg NAME "docker-compose-$PLATFORM" \
        '.name, .tag_name, (.assets[] | select (.name==$NAME) | .browser_download_url)'`)

# Download Docker Compose
# Example:
# https://github.com/docker/compose/releases/download/1.23.1/docker-compose-Linux-x86_64
VERSION="${GITHUB_META[0]}"
TAG="${GITHUB_META[1]}"
DOWNLOAD_URL="${GITHUB_META[2]}"
echo "Installing Docker Compose version: $VERSION" >&2
echo "Using download url: $DOWNLOAD_URL" >&2
# -O: Output file
wget -O "$TMPDIR/docker-compose-$PLATFORM" "$DOWNLOAD_URL"

# Install Docker Compose
sudo install "$TMPDIR/docker-compose-$PLATFORM" /usr/local/bin/docker-compose

# Install Docker Compose completions
# Example:
# https://raw.githubusercontent.com/docker/compose/1.23.1/contrib/completion/bash/docker-compose
for file in docker-compose ; do
    # -P: Prefix directory
    sudo wget "`eval echo $REPOS_URL_TMPL/contrib/completion/bash/$file`" \
        -P /etc/bash_completion.d
done
