#!/usr/bin/env bash

# GitHub api rate check:
# curl https://api.github.com/rate_limit

set -eou pipefail

PLATFORM="`uname -s`-`uname -m`"    # e.g. Linux-x86_64

DOCKER_CE_VERSION=                  # in format "vMAJOR.MINOR.PATCH"
DOCKER_CE_META_URL="https://api.github.com/repos/docker/docker-ce/releases/latest"
DOCKER_CE_URL_TMPL='https://raw.githubusercontent.com/docker/docker-ce/$DOCKER_CE_VERSION'

DOCKER_MACHINE_VERSION=             # in format "vMAJOR.MINOR.PATCH"
DOCKER_MACHINE_META_URL="https://api.github.com/repos/docker/machine/releases/latest"
DOCKER_MACHINE_META=
DOCKER_MACHINE_DOWNLOAD_URL=
DOCKER_MACHINE_URL_TMPL='https://raw.githubusercontent.com/docker/machine/$DOCKER_MACHINE_VERSION'

# Create temporary working directory
# Delete it on exit
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# Install Docker

# Get latest Docker release version using GitHub api
# Curl returns: { name: <version> }
# jq -r: Get raw strings ( no quotes )
DOCKER_CE_VERSION="`curl -s "$DOCKER_CE_META_URL" | jq -r .name`"
echo "Installing Docker $DOCKER_CE_VERSION" >&2

# Remove older version of docker that might have
# come bundled with the OS
sudo apt-get remove -y \
    docker \
    docker-engine \
    docker.io

# Install Dockers GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | sudo apt-key add -

# Add Docker repository
sudo add-apt-repository -y \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update -y

# Install Docker CE
# This will create the docker group
# and setup the docker service to autostart
sudo apt-get install docker-ce

# Add current user to docker group
# Note this wont take affect until subsequent login
sudo usermod -aG docker "$USER"

# Install Docker Bash completions
# Example
# https://raw.githubusercontent.com/docker/docker-ce/v18.09.0/components/cli/contrib/completion/bash/docker
curl -s "`eval echo $DOCKER_CE_URL_TMPL/components/cli/contrib/completion/bash/docker`" \
    | sudo tee /etc/bash_completion.d/docker.sh >/dev/null

# Install Docker Machine

# Get docker machine meta into array as follows:
# 0: version
# 1: download url
# Curl returns: {
#   name: <version>,
#   assets: [ { name: docker-machine-<platform>, browser_download_url: <url> } ] }
DOCKER_MACHINE_META=(`curl -s "$DOCKER_MACHINE_META_URL" \
        | jq -r --arg NAME "docker-machine-$PLATFORM" '.name, (.assets[] | select (.name==$NAME) | .browser_download_url)'`)

# Download Docker Machine
# Example:
# # https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-Linux-x86_64
DOCKER_MACHINE_VERSION="${DOCKER_MACHINE_META[0]}"
DOCKER_MACHINE_DOWNLOAD_URL="${DOCKER_MACHINE_META[1]}"
echo "Installing Docker Machine $DOCKER_MACHINE_VERSION" >&2
echo "Using download url: $DOCKER_MACHINE_DOWNLOAD_URL" >&2
# -O: Output file
wget -O "$TMPDIR/docker-machine-$PLATFORM" "$DOCKER_MACHINE_DOWNLOAD_URL"

# Install Docker Machine
ls -al "$TMPDIR/"
sudo install "$TMPDIR/docker-machine-$PLATFORM" /usr/local/bin/docker-machine

# Install Docker Machine completions and wrapper scripts
# Example:
# https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash
for file in docker-machine-wrapper.bash docker-machine.bash
do
    # -P: Prefix directory
    sudo wget "`eval echo $DOCKER_MACHINE_URL_TMPL/contrib/completion/bash/$file`" \
        -P /etc/bash_completion.d
done
