#!/usr/bin/env bash

echo "Verifying docker installation" >&2

# Verify that the docker installation has succeededs
docker run hello-world || exit

# Verify docker machine installation has successed
docker-machine --version || exit