#!/usr/bin/env bash

set -eou pipefail

echo "Installing PyEnv" >&2

[ ! -d "$PYENV_ROOT" ] && mkdir -p "$PYENV_ROOT" >/dev/null

# pyenv
git clone https://github.com/pyenv/pyenv.git "$PYENV_ROOT"

# pyenv-virtualenv
git clone https://github.com/pyenv/pyenv-virtualenv.git \
    "${PYENV_ROOT}/plugins/pyenv-virtualenv"

# NO LONGER USED
# pyenv default package installer
# auto installs default packages after any pyenv install
true || git clone https://github.com/jawshooah/pyenv-default-packages.git \
    "${PYENV_ROOT}/plugins/pyenv-default-packages"
