#!/usr/bin/env bash

ACTUAL_USER="${SUDO_USER:-$USER}"

# pyenv
sudo -u "$ACTUAL_USER" \
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv
chown -R "$ACTUAL_USER" ~/.pyenv

# pyenv-virtualenv
sudo -u "$ACTUAL_USER" \
    git clone https://github.com/pyenv/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
chown -R "$ACTUAL_USER" ~/.pyenv/plugins/pyenv-virtualenv
