#!/usr/bin/env bash

set -eou pipefail

echo "Installing PyEnv" >&2

[ ! -d "$PYENV_ROOT" ] && mkdir -p "$PYENV_ROOT" >/dev/null

# pyenv
git clone https://github.com/pyenv/pyenv.git "$PYENV_ROOT"

# pyenv-virtualenv
git clone https://github.com/pyenv/pyenv-virtualenv.git \
    "${PYENV_ROOT}/plugins/pyenv-virtualenv"
