#!/bin/bash

# Activation / deactivation of virtual envs requires
# pyenv to have been init in the executing shell
source ~/.bash_profile

# Install latest CPython and miniconda distributions
pyenv-wrapper install
pyenv-wrapper install miniconda3

# Create virtualenv for global Python and packages
# using the latest available Python 3
pyenv virtualenv \
    `pyenv whence 2to3 \
    | grep -e "^3" \
    | sort -k1Vr \
    | head` \
    global

# Install base packages into the new global virtualenv
pyenv activate global
pip install pipenv
pip install awscli
pyenv deactivate

# Set global Python environment to use the following environments
# in the following order
# This allows packages installed into the new global virtual
# environment to be called without implicitly activiating it
pyenv global system global
