#!/usr/bin/env bash

# NODENV installer

set -eou pipefail

echo "Installing nodenv" >&2

[ ! -d "$NODENV_ROOT" ] && mkdir -p "$NODENV_ROOT" >/dev/null

# Install nodenv
git clone https://github.com/nodenv/nodenv.git "$NODENV_ROOT"

# Compile dynamic bash nodenv extension
cd "$NODENV_ROOT" && src/configure && make -C src

# Install node-build to get the `nodenv install` command
[ ! -d "$NODENV_ROOT/plugins" ] && mkdir -p "$NODENV_ROOT/plugins" >/dev/null
git clone https://github.com/nodenv/node-build.git \
    "$NODENV_ROOT/plugins/node-build"
