#!/bin/bash

set -eou pipefail

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# Download latest nvm release
curl -s https://api.github.com/repos/creationix/nvm/releases/latest \
| grep "tarball_url" \
| cut -d '"' -f 4 \
| xargs -n1 wget -q -O "$TMPDIR/nvm.tar.gz"

# Unzip the latest release
mkdir "$TMPDIR/nvm"
tar -xzf "$TMPDIR/nvm.tar.gz" --directory "$TMPDIR/nvm"

# Find and run the installer
# Create a tmp shell dotfile and point the install script PROFILE
# variable at it to prevent the installer writing into the users shell dotfiles
touch "$TMPDIR/.profile"
find "$TMPDIR/nvm" -name "install.sh" \
| PROFILE="$TMPDIR/.profile" bash >/dev/null
