#!/usr/bin/env bash

# Not in interactive shell so need to boostrap NVM
# ( see shell dotfiles )
source "$DOTFILES_CONFIG_HOME/bash_nvm.sh"

echo "Provisioning NodeJS environment" >&2

# Install latest version of node
nvm install node

# Install specific named versions of node
nvm install 8
nvm install 10

# Set the default version to the lastest installed NodeJS version
nvm alias default node
