#!/usr/bin/env bash

# NODENV NodeJS provisioner

# Not in interactive shell so need to boostrap nodenv
# ( see shell dotfiles )
source "$DOTFILES_CONFIG_HOME/bash_nodenv.sh"

echo "Provisioning NodeJS environment" >&2

# Verify rbenv installation using rbenv-doctor
curl -fsSL https://github.com/nodenv/nodenv-installer/raw/master/bin/nodenv-doctor \
    | bash

# Install latest NodeJS distributions
xenv -c nodenv -v 10.*.* install
xenv -c nodenv install
