#!/bin/bash

# Start nvm
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Install latest version of node
nvm install node

# Install specific named versions of node
nvm install 8
nvm install 10

# Set the default version
nvm alias default node
